import { useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useAppStore } from "@/lib/app-store";
import type { AttendanceCategory, CategoryMode } from "@/shared/attendance";

const blue="#3155D9", navy="#111827", muted="#687386", coral="#C94B4B";
const modes: { value: CategoryMode; title: string; detail: string }[] = [
  { value: "both", title: "Present + Total", detail: "Counts attended time and attendance-required time." },
  { value: "presentOnly", title: "Present only", detail: "Boosts present hours without adding a required hour." },
  { value: "totalOnly", title: "Total only", detail: "Adds an attendance-required hour without present credit." },
  { value: "excluded", title: "Excluded", detail: "Does not affect attendance calculations." },
];

export default function CategoriesScreen() {
  const store = useAppStore();
  const [editingId, setEditingId] = useState<string | null>(null);
  const [name, setName] = useState(""); const [mode, setMode] = useState<CategoryMode>("both"); const [reassignTo, setReassignTo] = useState("");
  const editing = useMemo(() => store.categories.find((category) => category.id === editingId), [editingId, store.categories]);
  const resetForm = () => { setEditingId(null); setName(""); setMode("both"); setReassignTo(""); };
  const startEdit = (category: AttendanceCategory) => { setEditingId(category.id); setName(category.name); setMode(category.mode); setReassignTo(""); };
  const save = () => {
    const clean = name.trim();
    if (!clean) return Alert.alert("Name required", "Give this attendance category a clear name.");
    if (store.categories.some((category) => category.id !== editingId && category.name.toLowerCase() === clean.toLowerCase())) return Alert.alert("Name already used", "Choose a distinct category name.");
    const apply = () => { const next = editingId ? store.categories.map((category) => category.id === editingId ? { ...category, name: clean, mode } : category) : [...store.categories, { id: `category-${Date.now()}`, name: clean, mode, color: blue }]; store.saveCategories(next); resetForm(); };
    if (editing && editing.mode !== mode) Alert.alert("Change calculation behavior?", "Existing marked classes will keep their saved historical attendance impact. New classes and unmarked future classes use this new behavior.", [{ text:"Cancel", style:"cancel" }, { text:"Apply change", onPress:apply }]); else apply();
  };
  const remove = (category: AttendanceCategory) => {
    const used = store.timetable.filter((event) => event.categoryId === category.id);
    if (used.length && !reassignTo) return Alert.alert("Reassignment required", `${used.length} timetable event${used.length === 1 ? " is" : "s are"} using this category. Select a replacement before deleting.`);
    Alert.alert("Delete category?", used.length ? `${used.length} events will be reassigned before this category is removed.` : "This cannot be undone.", [{ text:"Cancel", style:"cancel" }, { text:"Delete", style:"destructive", onPress:() => { if (used.length) store.saveTimetable(store.timetable.map((event) => event.categoryId === category.id ? { ...event, categoryId: reassignTo } : event)); store.saveCategories(store.categories.filter((item) => item.id !== category.id)); resetForm(); } }]);
  };
  const replacements = store.categories.filter((category) => category.id !== editingId);
  return <ScreenContainer containerClassName="bg-[#F7F8FA]" className="px-5"><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>ATTENDANCE RULES</Text><Text style={styles.title}>Attendance categories</Text><Text style={styles.copy}>Set exactly how each activity affects attendance. Marked classes retain their historical calculation result if you change a rule later.</Text>{store.categories.map((category) => <Pressable key={category.id} onPress={() => startEdit(category)} style={[styles.category,{borderColor:editingId===category.id?blue:"#E7EAF0"}]}><View style={[styles.dot,{backgroundColor:category.color}]} /><View style={{flex:1}}><Text style={styles.categoryName}>{category.name}</Text><Text style={styles.muted}>{modes.find((item) => item.value===category.mode)?.title}</Text></View><Text style={styles.edit}>Edit</Text></Pressable>)}<View style={styles.form}><Text style={styles.formTitle}>{editing ? `Edit ${editing.name}` : "Add a category"}</Text><Text style={styles.label}>Category name</Text><TextInput value={name} onChangeText={setName} placeholder="e.g. Lab session" placeholderTextColor="#A0A8B5" style={styles.input}/><Text style={styles.label}>Calculation behavior</Text>{modes.map((item) => <Pressable key={item.value} onPress={() => setMode(item.value)} style={[styles.mode,mode===item.value&&styles.modeActive]}><View style={[styles.radio,mode===item.value&&styles.radioActive]}>{mode===item.value?<View style={styles.radioDot}/>:null}</View><View style={{flex:1}}><Text style={styles.modeTitle}>{item.title}</Text><Text style={styles.muted}>{item.detail}</Text></View></Pressable>)}{editing && store.timetable.some((event)=>event.categoryId===editing.id) ? <View style={styles.reassign}><Text style={styles.reassignTitle}>Reassign before deletion</Text><Text style={styles.muted}>Choose where existing timetable events should move if you delete this category.</Text><View style={styles.chips}>{replacements.map((category)=><Pressable key={category.id} onPress={()=>setReassignTo(category.id)} style={[styles.chip,reassignTo===category.id&&styles.chipActive]}><Text style={[styles.chipText,reassignTo===category.id&&styles.chipTextActive]}>{category.name}</Text></Pressable>)}</View></View>:null}<View style={styles.actions}><Pressable onPress={save} style={styles.save}><Text style={styles.saveText}>{editing?"Save category":"Add category"}</Text></Pressable>{editing?<Pressable onPress={()=>remove(editing)} style={styles.delete}><Text style={styles.deleteText}>Delete</Text></Pressable>:null}{editing?<Pressable onPress={resetForm} style={styles.cancel}><Text style={styles.cancelText}>Cancel</Text></Pressable>:null}</View></View></ScrollView></ScreenContainer>;
}

const styles=StyleSheet.create({content:{paddingTop:18,paddingBottom:34},back:{fontSize:16,color:blue,fontWeight:"700",marginBottom:24},eyebrow:{fontSize:11,letterSpacing:1.2,color:blue,fontWeight:"800",marginBottom:8},title:{fontSize:30,fontWeight:"800",color:navy},copy:{fontSize:14,lineHeight:21,color:muted,marginTop:10,marginBottom:18},category:{backgroundColor:"#FFF",borderRadius:15,padding:14,borderWidth:1,flexDirection:"row",alignItems:"center",marginBottom:8,gap:10},dot:{width:11,height:11,borderRadius:6},categoryName:{fontSize:15,fontWeight:"800",color:navy,marginBottom:2},muted:{fontSize:12,lineHeight:17,color:muted},edit:{fontSize:12,fontWeight:"800",color:blue},form:{marginTop:17,backgroundColor:"#FFF",borderRadius:20,padding:16,borderWidth:1,borderColor:"#E7EAF0"},formTitle:{fontSize:18,fontWeight:"800",color:navy,marginBottom:14},label:{fontSize:11,color:muted,fontWeight:"800",textTransform:"uppercase",letterSpacing:.5,marginBottom:7,marginTop:10},input:{borderWidth:1,borderColor:"#D8DDE7",borderRadius:11,padding:11,fontSize:15,color:navy},mode:{flexDirection:"row",gap:10,padding:11,borderWidth:1,borderColor:"#E7EAF0",borderRadius:12,marginTop:7},modeActive:{borderColor:blue,backgroundColor:"#F0F3FF"},radio:{width:18,height:18,borderRadius:9,borderWidth:1.5,borderColor:"#AAB4C6",alignItems:"center",justifyContent:"center",marginTop:2},radioActive:{borderColor:blue},radioDot:{width:9,height:9,borderRadius:5,backgroundColor:blue},modeTitle:{fontSize:13,color:navy,fontWeight:"800",marginBottom:2},reassign:{backgroundColor:"#FFF7E6",borderRadius:12,padding:12,marginTop:14},reassignTitle:{color:"#B7791F",fontWeight:"800",marginBottom:4},chips:{flexDirection:"row",flexWrap:"wrap",gap:6,marginTop:9},chip:{borderWidth:1,borderColor:"#D8DDE7",borderRadius:9,paddingVertical:7,paddingHorizontal:8,backgroundColor:"#FFF"},chipActive:{borderColor:blue,backgroundColor:"#EEF2FF"},chipText:{fontSize:11,color:muted,fontWeight:"700"},chipTextActive:{color:blue},actions:{flexDirection:"row",gap:8,marginTop:16},save:{flex:1,backgroundColor:blue,borderRadius:12,padding:13,alignItems:"center"},saveText:{color:"#FFF",fontWeight:"800"},delete:{borderRadius:12,borderWidth:1,borderColor:"#E8B4B0",paddingHorizontal:13,justifyContent:"center"},deleteText:{color:coral,fontWeight:"800"},cancel:{borderRadius:12,paddingHorizontal:8,justifyContent:"center"},cancelText:{color:muted,fontWeight:"800"}});
