import { useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import * as XLSX from "xlsx";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useAppStore } from "@/lib/app-store";
import { parseTimetableText } from "@/shared/attendance";
const blue="#3155D9", navy="#111827", muted="#687386", coral="#C94B4B";
export default function ImportScreen(){const store=useAppStore();const [loading,setLoading]=useState(false);const [error,setError]=useState(""); const pick=async()=>{setError("");setLoading(true);try{const result=await DocumentPicker.getDocumentAsync({type:["image/*","application/pdf","text/csv","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.ms-excel"],copyToCacheDirectory:true});if(result.canceled)return;const asset=result.assets[0];let text="";if(asset.name.match(/\.(csv|txt)$/i)&&asset.file){text=await asset.file.text();}else if(asset.name.match(/\.(xlsx|xls)$/i)){const response=await fetch(asset.uri);const buffer=await response.arrayBuffer();const workbook=XLSX.read(buffer,{type:"array"});text=XLSX.utils.sheet_to_csv(workbook.Sheets[workbook.SheetNames[0]]);}else{throw new Error("Image and PDF extraction needs OCR access. You can use a CSV/XLSX timetable now, or start with a blank timetable and enter each class manually.");}const events=parseTimetableText(text,store.categories);if(!events.length)throw new Error("No timetable rows could be recognized.");router.push({pathname:"/review",params:{events:JSON.stringify(events)}});}catch(e){setError(e instanceof Error?e.message:"We could not read that file. Try a CSV or spreadsheet.");}finally{setLoading(false);}};return <ScreenContainer containerClassName="bg-[#F7F8FA]" className="px-5"><ScrollView contentContainerStyle={styles.content}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>TIMETABLE SETUP</Text><Text style={styles.title}>Bring your week with you.</Text><Text style={styles.copy}>Upload an image, PDF, or spreadsheet. We’ll extract the schedule, then let you review every row before it affects your attendance.</Text><View style={styles.info}><Text style={styles.infoTitle}>Your data stays yours</Text><Text style={styles.muted}>Imported timetable data is stored locally on this device. Nothing is counted until you confirm the review.</Text></View><Pressable onPress={pick} disabled={loading} style={({pressed})=>[styles.drop,pressed&&{opacity:.8}]}><Text style={styles.dropIcon}>↑</Text><Text style={styles.dropTitle}>{loading?"Reading timetable…":"Choose a timetable file"}</Text><Text style={styles.muted}>PNG, JPG, PDF, CSV, XLSX</Text>{loading&&<ActivityIndicator color={blue} style={{marginTop:14}}/>}</Pressable>{error?<View style={styles.error}><Text style={styles.errorTitle}>Couldn’t import this file</Text><Text style={styles.errorCopy}>{error}</Text></View>:null}<Text style={styles.or}>or</Text><Pressable onPress={()=>router.push({pathname:"/review",params:{events:JSON.stringify([])}})} style={styles.manual}><Text style={styles.manualText}>Start with a blank timetable →</Text></Pressable></ScrollView></ScreenContainer>}
const styles=StyleSheet.create({content:{paddingTop:18,paddingBottom:34},back:{fontSize:16,color:blue,fontWeight:"700",marginBottom:24},eyebrow:{fontSize:11,letterSpacing:1.2,color:blue,fontWeight:"800",marginBottom:8},title:{fontSize:31,lineHeight:37,fontWeight:"800",color:navy},copy:{color:muted,fontSize:15,lineHeight:23,marginTop:12},info:{backgroundColor:"#EEF2FF",borderRadius:16,padding:15,marginTop:22},infoTitle:{color:blue,fontWeight:"800",marginBottom:5},muted:{color:muted,fontSize:13,lineHeight:19},drop:{backgroundColor:"#FFF",borderRadius:22,borderWidth:1.5,borderColor:"#AEBBF1",borderStyle:"dashed",alignItems:"center",paddingVertical:32,marginTop:22},dropIcon:{fontSize:30,color:blue,fontWeight:"700",marginBottom:8},dropTitle:{color:navy,fontSize:16,fontWeight:"800",marginBottom:5},error:{backgroundColor:"#FFF0EF",borderRadius:15,padding:14,marginTop:14},errorTitle:{color:coral,fontWeight:"800",marginBottom:4},errorCopy:{color:navy,fontSize:13,lineHeight:19},or:{textAlign:"center",color:muted,marginVertical:17},manual:{alignItems:"center",padding:13},manualText:{color:blue,fontWeight:"800"}});
