import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useAppStore } from "@/lib/app-store";
import { WEEKDAYS, type AttendanceState } from "@/shared/attendance";

const blue = "#3155D9"; const navy = "#111827"; const muted = "#687386";
const states: AttendanceState[] = ["present", "absent", "excused", "ignored"];
export default function CalendarScreen() { const store = useAppStore(); const [selectedDay, setSelectedDay] = useState(new Date().getDay()); const events = useMemo(() => store.timetable.filter((e) => e.weekday === selectedDay).sort((a,b) => a.startTime.localeCompare(b.startTime)), [store.timetable, selectedDay]);
return <ScreenContainer containerClassName="bg-[#F7F8FA]" className="px-5"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.top}><View><Text style={styles.eyebrow}>YOUR WEEK</Text><Text style={styles.title}>Calendar</Text></View><Pressable onPress={() => router.push("/import")} style={styles.add}><Text style={styles.addText}>＋ Import</Text></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.days}>{WEEKDAYS.slice(1).concat(WEEKDAYS.slice(0,1)).map((day, i) => { const dayIndex = (i + 1) % 7; return <Pressable key={day} onPress={() => setSelectedDay(dayIndex)} style={[styles.day, selectedDay === dayIndex && styles.dayActive]}><Text style={[styles.dayName, selectedDay === dayIndex && styles.activeText]}>{day.slice(0,3)}</Text><Text style={[styles.dayNumber, selectedDay === dayIndex && styles.activeText]}>{dayIndex === new Date().getDay() ? "•" : ""}</Text></Pressable>})}</ScrollView>{events.length === 0 ? <View style={styles.empty}><Text style={styles.emptyIcon}>◷</Text><Text style={styles.emptyTitle}>No classes on {WEEKDAYS[selectedDay]}</Text><Text style={styles.emptyCopy}>Import your timetable to see classes here, then mark each one as you go.</Text><Pressable onPress={() => router.push("/import")}><Text style={styles.link}>Import timetable →</Text></Pressable></View> : events.map((event) => { const record = store.records.find((r) => r.eventId === event.id); const state = record?.state; return <View key={event.id} style={styles.event}><View style={styles.time}><Text style={styles.timeText}>{event.startTime}</Text><Text style={styles.duration}>{event.duration}h</Text></View><View style={styles.eventBody}><Text style={styles.subject}>{event.subject}</Text><Text style={styles.category}>{store.categories.find((c) => c.id === event.categoryId)?.name ?? "Class"}</Text><View style={styles.stateRow}>{states.map((item) => <Pressable key={item} onPress={() => store.markAttendance({ eventId: event.id, state: item, date: new Date().toISOString() })} style={[styles.state, state === item && { backgroundColor: item === "present" ? "#EAF7F1" : item === "absent" ? "#FFF0EF" : "#EEF2FF", borderColor: item === "present" ? "#9BD6B8" : item === "absent" ? "#F0B7B1" : "#B8C3F7" }]}><Text style={[styles.stateText, state === item && { color: item === "present" ? "#168A5B" : item === "absent" ? "#C94B4B" : blue }]}>{item[0].toUpperCase() + item.slice(1)}</Text></Pressable>)}</View></View></View>})}</ScrollView></ScreenContainer>; }
const styles=StyleSheet.create({content:{paddingTop:18,paddingBottom:32},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:20},eyebrow:{fontSize:11,letterSpacing:1.2,color:blue,fontWeight:"800",marginBottom:7},title:{fontSize:30,fontWeight:"800",color:navy},add:{backgroundColor:blue,borderRadius:13,paddingHorizontal:13,paddingVertical:10},addText:{color:"#FFF",fontWeight:"800",fontSize:13},days:{gap:8,paddingBottom:22},day:{width:55,height:65,borderRadius:16,backgroundColor:"#FFF",alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"#E7EAF0"},dayActive:{backgroundColor:blue,borderColor:blue},dayName:{color:muted,fontSize:12,fontWeight:"700"},dayNumber:{color:muted,fontSize:18,fontWeight:"800",marginTop:6},activeText:{color:"#FFF"},empty:{backgroundColor:"#FFF",borderRadius:22,padding:26,alignItems:"center",marginTop:5,borderWidth:1,borderColor:"#E7EAF0"},emptyIcon:{fontSize:38,color:blue,marginBottom:12},emptyTitle:{fontSize:18,fontWeight:"800",color:navy},emptyCopy:{color:muted,fontSize:14,lineHeight:21,textAlign:"center",marginTop:8},link:{color:blue,fontWeight:"800",marginTop:16},event:{backgroundColor:"#FFF",borderRadius:18,padding:15,marginBottom:12,borderWidth:1,borderColor:"#E7EAF0",flexDirection:"row",gap:13},time:{width:48},timeText:{fontSize:13,fontWeight:"800",color:navy},duration:{fontSize:11,color:muted,marginTop:5},eventBody:{flex:1},subject:{fontSize:16,fontWeight:"800",color:navy},category:{fontSize:12,color:muted,marginTop:3},stateRow:{flexDirection:"row",flexWrap:"wrap",gap:5,marginTop:13},state:{borderWidth:1,borderColor:"#E7EAF0",borderRadius:8,paddingHorizontal:7,paddingVertical:6},stateText:{fontSize:10,color:muted,fontWeight:"700"}});
